version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:5000:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gurkbotdb
      POSTGRES_PASSWORD: gurkbotdb

    volumes:
      - ./bot/postgres/tables:/docker-entrypoint-initdb.d/

  gurkbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gurkbot
    init: true

    restart: always

    environment:
      - DATABASE_URL=postgres://gurkbotdb:gurkbotdb@postgres:5432/postgres
      - GUILD_ID
      - TOKEN
      - PREFIX
      - CHANNEL_OFF_TOPIC
      - CHANNEL_DEVLOG
      - CHANNEL_DEVALERTS
      - CHANNEL_DEV_GURKBOT
      - CHANNEL_DEV_REAGURK
      - CHANNEL_DEV_GURKLANG
      - CHANNEL_DEV_BRANDING

    volumes:
      - .:/bot

    depends_on:
      - postgres
